# Generated by Django 5.0.1 on 2024-01-09 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimages')),
                ('upload_date', models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 31, 0, 943099, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
