# Generated by Django 5.0.1 on 2024-01-09 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_alter_image_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 23, 40, 2, 732844, tzinfo=datetime.timezone.utc)),
        ),
    ]
